### PR TITLE
Update from upstream

### PR DESCRIPTION
**Pull request by Morilli**
Rebased the bizhawk specific changes from the 2.1 branch onto upstream master. I can't actually pull request to a new, non-existent branch so feel free to cherry-pick and push to a new branch manually.

### CODE REVIEW

**Comment by vadosnaprimer** [comment]
Thanks!

I've given you write privs (still rely on PRs for tasvideos branches), also I created the 2.2 branch and repointed the PR to it.

**Comment by Morilli** [comment]
Hmm the branch looks kinda wrong now...

**Comment by vadosnaprimer** [comment]
Direct merge was disabled so I used rebase (since we don't want to squash upstream commits) but now it appears as if I cherrypicked them all. Maybe for such cases merge should be available.

EDIT: Wait `8 commits ahead, 8 commits behind` wtf

**Comment by Morilli** [comment]
I think the branch should have been based on upstream's master initially instead of the state of tasvideos-2.1.

Might as well force push it to upstream's master and then cherry-pick 9fb7e67 or e6198c1b6a4f839cdd2ddf37da57c2c398700b0d on top of it.

**Comment by Morilli** [comment]
I have just force pushed the branch to a proper state; should be fine as it isn't used anywhere yet.

**Comment by vadosnaprimer** [comment]
Thanks!

**Pull request merged**
